# Generated by Django 5.2.3 on 2025-07-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_producto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento (0-100)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta_habilitada',
            field=models.BooleanField(default=False),
        ),
    ]
