# Generated by Django 5.2.3 on 2025-07-26 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_producto_descuento_producto_oferta_habilitada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='oferta_habilitada',
        ),
    ]
