# Generated by Django 5.2.3 on 2025-07-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_producto_descuento_producto_en_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_anterior', to='shop.categoria'),
        ),
    ]
