# Generated by Django 5.2.3 on 2025-07-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_producto_categoria_anterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_anterior',
        ),
    ]
