# Generated by Django 5.1 on 2025-08-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Unidades disponibles en inventario'),
        ),
    ]
