# Generated by Django 5.1 on 2025-10-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_solicitudservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
