# Generated by Django 5.1 on 2025-10-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_solicitudservicio_fecha_solicitudservicio_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='fecha_propuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='hora_propuesta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='ultima_propuesta_por',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('negociacion', 'Negociación')], default='pendiente', max_length=15),
        ),
    ]
