# Generated by Django 5.1 on 2025-10-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_solicitudservicio_fecha_propuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular_contacto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion_perfil',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion_local',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiene_local',
            field=models.BooleanField(default=False),
        ),
    ]
