# Generated by Django 5.1 on 2025-10-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_city_usuario_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='shop.city'),
        ),
    ]
