# Generated by Django 5.1 on 2025-10-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_producto_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='enviado',
            field=models.BooleanField(default=False, help_text='El vendedor marcó este producto como enviado'),
        ),
    ]
