# Generated by Django 5.1 on 2025-10-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='calificacion_comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='calificacion_valor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
