# Generated by Django 5.2.4 on 2025-10-16 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_producto_average_rating_producto_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('usuario', 'solicitud_servicio')},
        ),
        migrations.AddField(
            model_name='calificacion',
            name='pedido_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='shop.pedidoitem'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('usuario', 'pedido_item'), ('usuario', 'solicitud_servicio')},
        ),
    ]
