# Generated by Django 5.1 on 2025-10-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_calificacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudservicio',
            name='barrio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='shop.city'),
        ),
        migrations.AddField(
            model_name='solicitudservicio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
