# Generated by Django 5.1 on 2025-10-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_pedido_entrega_barrio_pedido_entrega_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='barrio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
