# Generated by Django 5.1 on 2025-10-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_usuario_barrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='precio_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario pagado (con descuento aplicado)', max_digits=10, null=True),
        ),
    ]
