# Generated by Django 5.1 on 2025-10-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_pedidoitem_precio_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
